🙈 fix not splitting 1. of May paragraph
transcribee/transcribee pull request #151
Opened 2023-05-10 18:14 UTC by anuejn

2023-05-10 18:49 UTC, phlmn requested changes

2023-05-10 18:49 UTC, phlmn commented on worker/transcribee_worker/identify_speakers.py
> +                # we always use at least 0.1s, otherwise the fingerprinting model explodes sometimes
looks like 0.5s to me?

2023-05-10 18:50 UTC, pajowu commented on worker/transcribee_worker/whisper_transcribe.py
> +                and len(acc_paragraph.children) > 0
This should be equivalent

2023-05-11 23:52 UTC, phlmn approved these changes

2023-05-12 00:00 UTC, merged