anuejn/confidence fix
transcribee/transcribee pull request #170
Opened 2023-05-17 21:25 UTC by anuejn

- 💅 use gradient for confidence colors
- 🚧 wip: set confidence to 1 on user correction

2023-05-21 17:24 UTC, pajowu requested changes
I'm not a big fan of this. While it it's nice to show the users the confidence in a more fine-grained way, i'm not sure doing it via the text color is the best way. I find it hard to judge the difference between the colors and to figure out the confidence from these.

The current formula for generating the colors also currently generates colors with contrast less than 4.5:1 ([WCAG 2.1 SC 1.4.3](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html))

2023-05-21 22:33 UTC, anuejn commented
the audapolis-way of doing things sadly looks a bit ugly because we already use bg-color to highlight the current word. What would you propose?

2023-05-21 22:38 UTC, anuejn commented on frontend/src/editor/transcription_editor.tsx
> +    : `hsl(0, 100%, ${Math.min((1 - leaf.conf) * 100, 50)}%)`;
```suggestion
    : `hsl(0, 100%, ${Math.min((1 - leaf.conf) * 100, 45)}%)`;
```

if we do this change we get the required contrast ratios for both light and dark

2023-05-23 14:58 UTC, anuejn commented
@pajowu is it okay for you now that the contrast ratio ist always more than 4.5:1 ?

2023-05-23 15:02 UTC, pajowu commented
I think using fixed buckets could be a better way (<0.7 red, <0.95 darker red, >0.95 black) or something like that? But I'm fine with merging this for now as long as the contrast is fine

2023-05-23 18:29 UTC, pajowu approved these changes

2023-05-23 19:08 UTC, merged