anuejn/version
transcribee/transcribee pull request #224
Opened 2023-05-25 21:00 UTC by anuejn

- ✨ add version API endpoint
- ✨ display current transcribee version in frontend
- 🐞 fix useStateDelayed rapid toggling
- 🐞 fix tooltip bottom arrow
- 🐞 close tooltip with delay

2023-05-30 09:10 UTC, pajowu commented on frontend/src/common/version.tsx
> +          Frontend build on {formatDate(version.date)}. {versionText}
```suggestion
          Frontend built on {formatDate(version.date)}. {versionText}
```

2023-05-30 09:13 UTC, pajowu requested changes
The version is currently not shown on the document editor page. Is this on purpose? I'd prefer to have it there as well

2023-05-30 09:13 UTC, pajowu commented on frontend/src/common/version.tsx
> +    </>
This could be a component

2023-05-30 09:13 UTC, pajowu commented on frontend/src/common/version.tsx
> +            lastCommit.date,
I feel like this is not proper english?

2023-05-30 09:31 UTC, rroohhh commented on frontend/src/common/version.tsx
> +        tooltipText={`until ${lastCommitOnMain.hash.substring(0, 10)} from ${formatDate(
Maybe a weird idea, but making this a link to github with the correct revision would be fun.
We could even implement a way to download the source that way.

2023-05-30 10:44 UTC, anuejn commented on frontend/src/common/version.tsx
> +            lastCommit.date,
any suggestions?

2023-05-31 08:39 UTC, pajowu approved these changes

2023-05-31 08:56 UTC, merged